on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20.3.0"

      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm fmt
      - run: pnpm e2e
